database:
    app:
        name:
        conn:
            host:
            port:
            user:
            password:
            stale_timeout: 300
            max_connections: 100

cors:
    allowed_origins:
        - 'http://localhost:4000'
